module.exports = {
  // --- Brasileirão Série A ---
  "Flamengo": "CR Flamengo",
  "Sport Recife": "SC Recife",
  "São Paulo": "São Paulo FC",
  "Cruzeiro": "Cruzeiro EC",
  "Grêmio": "Grêmio FBPA",
  "Fluminense": "Fluminense FC",
  "Botafogo-RJ": "Botafogo FR",
  "Juventude-RS": "EC Juventude",
  "Bragantino": "RB Bragantino",
  "Bahia": "EC Bahia",
  "Santos": "Santos FC",
  "Vitória": "EC Vitória",
  "Ceará": "Ceará SC",
  "Atlético-MG": "CA Mineiro",
  "Corinthians": "SC Corinthians Paulista",
  "Internacional": "SC Internacional",
  "Mirassol": "Mirassol FC",
  "Vasco da Gama": "CR Vasco da Gama",
  "Fortaleza": "Fortaleza EC",
  "Palmeiras": "SE Palmeiras",

  // --- Brasileirão Série B ---
  "Amazonas AM": "Amazonas FC AM",
  "América-MG": "América MG",
  "Athletico-PR": "Athletico Paranaense",
  "Atlético-GO": "Atlético Goianiense",
  "Grêmio Novorizontino": "Grêmio Novorizontino",
  "Avaí": "Avaí SC",
  "CRB": "CRB Maceió",
  "Coritiba": "Coritiba PR",
  "Volta Redonda": "Volta Redonda RJ",
  "Vila Nova": "Vila Nova GO",
  "Paysandu": "Paysandu SC",
  "Remo": "Remo PA",
  "Criciúma": "Criciúma EC",
  "Operário-PR": "Operário PR",
  "Ferroviária": "Ferroviária SP",
  "Botafogo-SP": "Botafogo SP",
  "Cuiabá": "Cuiabá EC",
  "Chapecoense": "Chapecoense AF",
  "Goiás": "Goiás GO",

  // --- Premier League ---
  "Arsenal": "Arsenal FC",
  "Aston Villa": "Aston Villa FC",
  "Chelsea": "Chelsea FC",
  "Liverpool": "Liverpool FC",
  "Manchester City": "Manchester City FC",
  "Manchester United": "Manchester United FC",
  "Newcastle United": "Newcastle United FC",
  "Tottenham": "Tottenham Hotspur FC",
  "West Ham United": "West Ham United FC",
  "Wolverhampton": "Wolverhampton Wanderers FC",
  "Leeds United": "Leeds United FC",
  "Everton": "Everton FC",
  "Crystal Palace": "Crystal Palace FC",
  "Fulham FC": "Fulham FC",
  "Brentford": "Brentford FC",
  "Nottingham Forest": "Nottingham Forest FC",
  "Brighton & Hove Albion": "Brighton & Hove Albion FC",
  "AFC Bournemouth": "Bournemouth AFC",
  "Burnley": "Burnley FC",
  "Sunderland": "Sunderland AFC",

  // --- Serie A ---
  "Fiorentina": "ACF Fiorentina",
  "Atalanta": "Atalanta BC",
  "Roma": "AS Roma",
  "Bologna FC": "Bologna FC 1909",
  "Cagliari": "Cagliari Calcio",
  "Como 1907": "Como 1907",
  "Genoa CFC": "Genoa CFC",
  "Hellas Verona": "Hellas Verona FC",
  "Inter de Milão": "Inter Milan",
  "Juventus FC": "Juventus FC",
  "Lazio": "Lazio SS",
  "Napoli": "SSC Napoli",
  "Parma Calcio 1913": "Parma Calcio 1913",
  "Udinese": "Udinese Calcio",
  "Sassuolo": "Sassuolo Calcio",
  "Torino": "Torino FC",
  "AC Pisa 1909": "Pisa Sporting Club",

  // --- Bundesliga ---
  "1. FC Heidenheim": "1. FC Heidenheim 1846",
  "1.FC Köln": "1. FC Köln",
  "1.FC Union Berlin": "1. FC Union Berlin",
  "Mainz 05": "1. FSV Mainz 05",
  "Bayer Leverkusen": "Bayer 04 Leverkusen",
  "Bayern de Munique": "Bayern Munich",
  "Borussia Dortmund": "Borussia Dortmund",
  "Borussia Monchengladbach": "Borussia Mönchengladbach",
  "Eintracht Frankfurt": "Eintracht Frankfurt",
  "Augsburg": "FC Augsburg",
  "FC St. Pauli": "FC St. Pauli",
  "Hamburgo": "Hamburger SV",
  "RB Leipzig": "RB Leipzig",
  "Freiburg": "SC Freiburg",
  "Werder Bremen": "SV Werder Bremen",
  "Hoffenheim": "TSG 1899 Hoffenheim",
  "VfB Stuttgart": "VfB Stuttgart",
  "Wolfsburg": "VfL Wolfsburg",

  // --- Ligue 1 ---
  "Monaco": "AS Monaco FC",
  "Angers": "Angers SCO",
  "Paris Saint Germain": "Paris Saint-Germain",
  "Paris FC": "Paris FC",
  "Lens": "RC Lens",
  "Nice": "OGC Nice",
  "Lyon": "Olympique Lyonnais",
  "Olympique de Marseille": "Olympique Marseille",
  "Estrasburgo": "RC Strasbourg Alsace",
  "Brestois": "Stade Brestois 29",
  "Rennes": "Stade Rennais FC",
  "AJ Auxerre": "AJ Auxerre",
  "Nantes": "FC Nantes",
  "FC Metz": "FC Metz",
  "FC Lorient": "FC Lorient",
  "Toulouse FC": "Toulouse FC",
  "Le Havre AC": "Le Havre AC",
  "Lille": "LOSC Lille",

  // --- La Liga ---
  "Real Madrid": "Real Madrid CF",
  "Barcelona": "FC Barcelona",
  "Atlético de Madrid": "Atlético de Madrid",
  "Osasuna": "CA Osasuna",
  "Celta de Vigo": "RC Celta Vigo",
  "Rayo Vallecano": "Rayo Vallecano",
  "Real Sociedad": "Real Sociedad",
  "Bétis": "Real Betis",
  "Girona FC": "Girona FC",
  "Getafe CF": "Getafe CF",
  "Elche": "Elche CF",
  "Mallorca": "Mallorca",
  "Levante": "Levante UD",
  "Valencia": "Valencia CF",
  "Sevilha FC": "Sevilla FC",
  "Villarreal CF": "Villarreal CF",
  "Real Oviedo": "Real Oviedo",
  "Deportivo Alavés": "Deportivo Alavés",

  // --- Champions League ---
  "AFC Ajax": "AFC Ajax (NED)",
  "Rangers FC": "Rangers FC",
  "Salzburg": "Red Bull Salzburg",
  "Estrela Vermelha": "Red Star Belgrade",
  "Servette FC": "Servette FC",
  "SK Brann": "SK Brann",
  "Slavia Praga": "Slavia Prague",
  "SK Sturm Graz": "SK Sturm Graz",
  "Sporting CP": "Sporting CP",
  "Club Brugge KV": "Club Brugge KV",
  "Dínamo Kiev": "Dynamo Kyiv",
  "Basel": "Basel",
  "FC Copenhagen": "FC Copenhagen",
  "FC Viktoria Plzen": "Viktoria Plzen",
  "FCSB": "FCSB",
  "Fenerbahce SK": "Fenerbahce",
  "Feyenoord": "Feyenoord Rotterdam",
  "FK Bodo/Glimt": "FK Bodo/Glimt",
  "Galatasaray": "Galatasaray",
  "HNK Rijeka": "HNK Rijeka",
  "FC Kairat": "Kairat",
  "Lech Poznan": "Lech Poznan",
  "Ludogorets": "Ludogorets",
  "Malmo FF": "Malmo FF",
  "Olympiacos": "Olympiacos",
  "Pafos FC": "Pafos FC",
  "Panathinaikos": "Panathinaikos",
  "PSV Eindhoven": "PSV Eindhoven",
};
