module.exports = {
  // --- Brasileirão Série A ---
  "CR Flamengo": "Flamengo",
  "SC Recife": "Sport Recife",
  "São Paulo FC": "São Paulo",
  "Cruzeiro EC": "Cruzeiro",
  "Grêmio FBPA": "Grêmio",
  "Fluminense FC": "Fluminense",
  "Botafogo FR": "Botafogo-RJ",
  "EC Juventude": "Juventude-RS",
  "RB Bragantino": "Bragantino",
  "EC Bahia": "Bahia",
  "Santos FC": "Santos",
  "EC Vitória": "Vitória",
  "Ceará SC": "Ceará",
  "CA Mineiro": "Atlético-MG",
  "SC Corinthians Paulista": "Corinthians",
  "SC Internacional": "Internacional",
  "Mirassol FC": "Mirassol",
  "CR Vasco da Gama": "Vasco da Gama",
  "Fortaleza EC": "Fortaleza",

  // --- Brasileirão Série B ---
  "Amazonas FC AM": "Amazonas AM",
  "América MG": "América-MG",
  "Athletico Paranaense": "Athletico-PR",
  "Atlético Goianiense": "Atlético-GO",
  "Grêmio Novorizontino": "Grêmio Novorizontino",
  "Avaí FC": "Avaí",
  "CRB Maceió": "CRB",
  "Coritiba FC": "Coritiba",
  "Volta Redonda RJ": "Volta Redonda",
  "Vila Nova GO": "Vila Nova",
  "Paysandu SC": "Paysandu",
  "Remo PA": "Remo",
  "Criciúma EC": "Criciúma",
  "Operário PR": "Operário-PR",
  "Ferroviária SP": "Ferroviária",
  "Botafogo SP": "Botafogo-SP",
  "Cuiabá EC": "Cuiabá",
  "Chapecoense AF": "Chapecoense",

  // --- Premier League ---
  "Arsenal FC": "Arsenal",
  "Aston Villa FC": "Aston Villa",
  "Chelsea FC": "Chelsea",
  "Liverpool FC": "Liverpool",
  "Manchester City FC": "Manchester City",
  "Manchester United FC": "Manchester United",
  "Newcastle United FC": "Newcastle United",
  "Tottenham Hotspur FC": "Tottenham",
  "West Ham United FC": "West Ham United",
  "Wolverhampton Wanderers FC": "Wolverhampton",
  "Leeds United FC": "Leeds United",
  "Everton FC": "Everton",
  "Crystal Palace FC": "Crystal Palace",
  "Fulham FC": "Fulham FC",
  "Brentford FC": "Brentford",
  "Nottingham Forest FC": "Nottingham Forest",
  "Brighton & Hove Albion FC": "Brighton & Hove Albion",
  "Bournemouth AFC": "AFC Bournemouth",
  "Burnley FC": "Burnley",
  "Sunderland AFC": "Sunderland",

  // --- Serie A ---
  "ACF Fiorentina": "Fiorentina",
  "Atalanta BC": "Atalanta",
  "AS Roma": "Roma",
  "Bologna FC 1909": "Bologna FC",
  "Cagliari Calcio": "Cagliari",
  "Como 1907": "Como 1907",
  "Genoa CFC": "Genoa CFC",
  "Hellas Verona FC": "Hellas Verona",
  "Inter Milan": "Inter de Milão",
  "Juventus FC": "Juventus FC",
  "Lazio SS": "Lazio",
  "SSC Napoli": "Napoli",
  "Parma Calcio 1913": "Parma Calcio 1913",
  "Udinese Calcio": "Udinese",
  "Sassuolo Calcio": "Sassuolo",
  "Torino FC": "Torino",
  "Pisa Sporting Club": "AC Pisa 1909",

  // --- Bundesliga ---
  "1. FC Heidenheim 1846": "1. FC Heidenheim",
  "1. FC Köln": "1.FC Köln",
  "1. FC Union Berlin": "1.FC Union Berlin",
  "1. FSV Mainz 05": "Mainz 05",
  "Bayer 04 Leverkusen": "Bayer Leverkusen",
  "Bayern Munich": "Bayern de Munique",
  "Borussia Dortmund": "Borussia Dortmund",
  "Borussia Mönchengladbach": "Borussia Monchengladbach",
  "Eintracht Frankfurt": "Eintracht Frankfurt",
  "FC Augsburg": "Augsburg",
  "FC St. Pauli": "FC St. Pauli",
  "Hamburger SV": "Hamburgo",
  "RB Leipzig": "RB Leipzig",
  "SC Freiburg": "Freiburg",
  "SV Werder Bremen": "Werder Bremen",
  "TSG 1899 Hoffenheim": "Hoffenheim",
  "VfB Stuttgart": "VfB Stuttgart",
  "VfL Wolfsburg": "Wolfsburg",

  // --- Ligue 1 ---
  "AS Monaco FC": "Monaco",
  "Angers SCO": "Angers",
  "Paris Saint-Germain": "Paris Saint Germain",
  "Paris FC": "Paris FC",
  "RC Lens": "Lens",
  "OGC Nice": "Nice",
  "Olympique Lyonnais": "Lyon",
  "Olympique Marseille": "Olympique de Marseille",
  "RC Strasbourg Alsace": "Estrasburgo",
  "Stade Brestois 29": "Brestois",
  "Stade Rennais FC": "Rennes",
  "AJ Auxerre": "AJ Auxerre",
  "FC Nantes": "Nantes",
  "FC Metz": "FC Metz",
  "FC Lorient": "FC Lorient",
  "Toulouse FC": "Toulouse FC",
  "Le Havre AC": "Le Havre AC",
  "LOSC Lille": "Lille",

  // --- La Liga ---
  "Real Madrid CF": "Real Madrid",
  "FC Barcelona": "Barcelona",
  "Atlético de Madrid": "Atlético de Madrid",
  "CA Osasuna": "Osasuna",
  "RC Celta Vigo": "Celta de Vigo",
  "Rayo Vallecano": "Rayo Vallecano",
  "Real Sociedad": "Real Sociedad",
  "Real Betis": "Bétis",
  "Girona FC": "Girona FC",
  "Getafe CF": "Getafe CF",
  "Elche CF": "Elche",
  "Mallorca": "Mallorca",
  "Levante UD": "Levante",
  "Valencia CF": "Valencia",
  "Sevilla FC": "Sevilha FC",
  "Villarreal CF": "Villarreal CF",
  "Real Oviedo": "Real Oviedo",
  "Deportivo Alavés": "Deportivo Alavés",

  // --- Champions League ---
  "AFC Ajax (NED)": "AFC Ajax",
  "Rangers FC": "Rangers FC",
  "Red Bull Salzburg": "Salzburg",
  "Red Star Belgrade": "Estrela Vermelha",
  "Servette FC": "Servette FC",
  "SK Brann": "SK Brann",
  "Slavia Prague": "Slavia Praga",
  "SK Sturm Graz": "SK Sturm Graz",
  "Sporting CP": "Sporting CP",
  "Club Brugge KV": "Club Brugge KV",
  "Dynamo Kyiv": "Dínamo Kiev",
  "Basel": "Basel",
  "FC Copenhagen": "FC Copenhagen",
  "Viktoria Plzen": "FC Viktoria Plzen",
  "FCSB": "FCSB",
  "Fenerbahce": "Fenerbahce SK",
  "Feyenoord Rotterdam": "Feyenoord",
  "FK Bodo/Glimt": "FK Bodo/Glimt",
  "Galatasaray": "Galatasaray",
  "HNK Rijeka": "HNK Rijeka",
  "Kairat": "FC Kairat",
  "Lech Poznan": "Lech Poznan",
  "Ludogorets": "Ludogorets",
  "Malmo FF": "Malmo FF",
  "Olympiacos": "Olympiacos",
  "Pafos FC": "Pafos FC",
  "Panathinaikos": "Panathinaikos",
  "PSV Eindhoven": "PSV Eindhoven",
};
